version: '3.7'
services:
  tslb02:
    image: tslb02
    ports:
      - "9987:9987/udp"
      - "10012:10012"
      - "30034:30034"
      - "41144:41144"
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - ts-data:/data

volumes:
  ts-data:
    driver: local
